Feat/fee 548 value formatter
keen/widget-customization pull request #9
Opened 2021-04-13 11:03 UTC by apryka

https://metakeen.atlassian.net/browse/FEE-548

2021-04-13 11:27 UTC, maciejrybaniec requested changes

2021-04-13 11:27 UTC, maciejrybaniec commented on src/serializers/serializeFormatterSettings.test.ts
> +  expect(result).toMatchInlineSnapshot(`""`);
Is empty `""` string is correct expected result in this test case ?

2021-04-13 11:37 UTC, maciejrybaniec commented on src/components/FormatValues/FormatValues.tsx
> +    1000,
I rather suggest to use `200` or `300` ms debounce time - as during testing a one second is providing a delay that can be easily see by the user.

2021-04-14 10:36 UTC, mczapkowicz approved these changes

2021-04-14 10:37 UTC, maciejrybaniec approved these changes

2021-04-14 10:38 UTC, merged